services:

  # =========================
  # NGINX LOAD BALANCER
  # =========================

  nginx:
    image: nginx:alpine
    container_name: url-shortener-nginx

    ports:
      - "8080:80"

    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - api1
      - api2
      - api3


  # =========================
  # NODE API INSTANCE 1
  # =========================

  api1:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: url-shortener-api-1

    expose:
      - "3000"

    environment:
      NODE_ENV: production
      PORT: 3000

      DATABASE_URL: postgresql://postgres:localdev@postgres:5432/balram
      PGPASSWORD: localdev

      REDIS_URL: redis://redis:6379
      IOREDIS_HOST: redis
      IOREDIS_PORT: 6379

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy


  # =========================
  # NODE API INSTANCE 2
  # =========================

  api2:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: url-shortener-api-2

    expose:
      - "3000"

    environment:
      NODE_ENV: production
      PORT: 3000

      DATABASE_URL: postgresql://postgres:localdev@postgres:5432/balram
      PGPASSWORD: localdev

      REDIS_URL: redis://redis:6379
      IOREDIS_HOST: redis
      IOREDIS_PORT: 6379

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy


  # =========================
  # NODE API INSTANCE 3
  # =========================

  api3:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: url-shortener-api-3

    expose:
      - "3000"

    environment:
      NODE_ENV: production
      PORT: 3000

      DATABASE_URL: postgresql://postgres:localdev@postgres:5432/balram
      PGPASSWORD: localdev

      REDIS_URL: redis://redis:6379
      IOREDIS_HOST: redis
      IOREDIS_PORT: 6379

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy


  # =========================
  # POSTGRESQL
  # =========================

  postgres:
    image: postgres:16-alpine

    container_name: url-shortener-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localdev
      POSTGRES_DB: balram

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d balram"
        ]

      interval: 5s
      timeout: 5s
      retries: 5


  # =========================
  # REDIS
  # =========================

  redis:
    image: redis:7-alpine

    container_name: url-shortener-redis

    ports:
      - "6380:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]

      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
  redis_data: