ALTER TABLE urls
  ADD COLUMN IF NOT EXISTS short_code VARCHAR(16),
  ADD COLUMN IF NOT EXISTS original_url TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS urls_short_code_unique_idx
  ON urls (short_code)
  WHERE short_code IS NOT NULL;
